Disable RobotSayHelp because it caused another error
```
2023-06-01T02:24:09.426816+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/ruboty-zoi-1.1.0/lib/ruboty/zoi.rb:38: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
2023-06-01T02:24:09.438743+00:00 app[bot.1]: E, [2023-06-01T02:24:09.438678 #2] ERROR -- : NoMethodError: undefined method `[]' for nil:NilClass
2023-06-01T02:24:09.438745+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/ruboty-slack_rtm-3.2.5/lib/ruboty/adapters/slack_rtm.rb:349:in `block in resolve_channel_id'
2023-06-01T02:24:09.438746+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/ruboty-slack_rtm-3.2.5/lib/ruboty/adapters/slack_rtm.rb:348:in `each_pair'
2023-06-01T02:24:09.438746+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/ruboty-slack_rtm-3.2.5/lib/ruboty/adapters/slack_rtm.rb:348:in `resolve_channel_id'
2023-06-01T02:24:09.438746+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/ruboty-slack_rtm-3.2.5/lib/ruboty/adapters/slack_rtm.rb:27:in `say'
2023-06-01T02:24:09.438748+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/ruboty-1.3.1/lib/ruboty/robot.rb:39:in `say'
2023-06-01T02:24:09.438749+00:00 app[bot.1]: main.rb:21:in `rescue in receive'
2023-06-01T02:24:09.438750+00:00 app[bot.1]: main.rb:18:in `receive'
2023-06-01T02:24:09.438750+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/ruboty-slack_rtm-3.2.5/lib/ruboty/adapters/slack_rtm.rb:172:in `on_message'
2023-06-01T02:24:09.438751+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/ruboty-slack_rtm-3.2.5/lib/ruboty/adapters/slack_rtm.rb:90:in `block in bind'
2023-06-01T02:24:09.438751+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/ruboty-slack_rtm-3.2.5/lib/ruboty/slack_rtm/client.rb:28:in `block in on_text'
2023-06-01T02:24:09.438751+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/event_emitter-0.2.6/lib/event_emitter/emitter.rb:53:in `instance_exec'
2023-06-01T02:24:09.438751+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/event_emitter-0.2.6/lib/event_emitter/emitter.rb:53:in `block in emit'
2023-06-01T02:24:09.438752+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/event_emitter-0.2.6/lib/event_emitter/emitter.rb:48:in `each'
2023-06-01T02:24:09.438752+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/event_emitter-0.2.6/lib/event_emitter/emitter.rb:48:in `emit'
2023-06-01T02:24:09.438752+00:00 app[bot.1]: /app/vendor/bundle/ruby/2.7.0/gems/websocket-client-simple-0.6.0/lib/websocket-client-simple/client.rb:60:in `block in connect'
```